@endpoint=http://localhost:{{$dotenv PORT}}

### Get All Events
GET {{endpoint}}/events


###

POST {{endpoint}}/events
Content-Type: application/json

{
    "name": "Event 1",
    "date": "2021-09-01",
    "organizer_id": 1
}

###

PUT {{endpoint}}/events/1
Content-Type: application/json

{
    "name": "Event 42",
    "date": "2021-09-01",
    "organizer_id": 3
}

###

DELETE {{endpoint}}/events/52